[package]
name = "twitter-cli"
version = "0.1.0"
authors = ["Ryo Kato <ryo_kato@hashedhyphen.com>"]

[dependencies]
base64 = "0.6.0"
futures = "0.1.14"
hyper = "0.11.2"
hyper-tls = "0.1.2"
rand = "0.3.16"
tokio-core = "0.1"
percent-encoding = "1.0.0"
regex = "0.2.2"
rust-crypto = "0.2.36"
